### ISSUE TITLE
(Bitcoin 0.9) Lower maximum size for free transaction creation

### ISSUE THREAD

**Issue by mjmacleod** [nlgcoin/guldencoin2#22]
Reconsider for gulden.

**Comment by Waterloodown** [comment]
The issue:
Currently, any transaction sending less than BTC0.01 absolutely requires a transaction fee of at least BTC0.0001. Assuming you want to transfer BTC0.00001 to your friend, not only will you have to pay this fee, but your friend will also have to pay an additional BTC0.0001 to send his coins anywhere else. Since the required fee is more than he has, he will not be able to spend his coins at all, and the whole situation is entirely your fault. 

This does not need to be lowered for gulden but it will in the future as value increases.

**Comment by cydg** [comment]
From my point of view: Let's keep it at the old NLG values as long as there is no real reason to change it.
