### ISSUE TITLE
IsDust

### ISSUE THREAD

**Issue by mjmacleod** [nlgcoin/guldencoin2#9]
See comment below - double check if this is still true and/or something we want.

// Guldencoin: IsDust() detection disabled, allows any valid dust to be relayed.
// The fees imposed on each dust txo is considered sufficient spam deterrant.

**Comment by Waterloodown** [comment]
From the below:
https://github.com/litecoin-project/litecoin/blob/master-0.10/doc/release-notes-litecoin.md

•Bitcoin's IsDust() is disabled in favor of Litecoin's fee-based dust penalty.
•Fee-based Dust Penalty: For each transaction output smaller than DUST_THRESHOLD (currently 0.001 LTC) the default relay/mining policy will expect an additional 1000 bytes of fee. Otherwise the transaction will be rejected from relay/mining. Such transactions are also disqualified from the free/high-priority transaction rule

Reason it got disabled:
* IsDust() is disabled because the per-dust fee penalty is considered to be sufficient deterrent.
https://github.com/litecoin-project/litecoin/commit/0d1d058451e8f27ffd4954a00e94825d680a1769

**Comment by cydg** [comment]
Haven't seen any chain bloat with 1Sat transactions, so let's keep it disabled

**Comment by mjmacleod** [comment]
Righto.
